import Head from 'next/head'

export default function Home() {
  return (
    <section>
      <Head>
        <title>Employees CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Employee Management</h1>
      </main>

    </section>
  )
}
