import Head from 'next/head'

export default function Home() {
  return (
    <section>
      <Head>
        <title>Employees CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold-py-10'>Employee Management</h1>
      </main>

    </section>
  )
}
